#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "lunaperche"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # guifont = "SourceCodePro Nerd Font Mono:h11"
    guifont = "Inconsolata Nerd Font"
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # filemanager = "defx"
    # filemanager = "neo-tree"
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
    project_rooter_outermost = false
# # All SpaceVim option below [option] section
# [options]
#     # set spacevim theme. by default colorscheme layer is not loaded,
#     # if you want to use more colorscheme, please load the colorscheme
#     # layer
#     colorscheme = "gruvbox"
#     colorscheme_bg = "dark"
#     # Disable guicolors in basic mode, many terminal do not support 24bit
#     # true colors
#     enable_guicolors = true
#     # Disable statusline separator, if you want to use other value, please
#     # install nerd fonts
#     statusline_separator = "arrow"
#     statusline_iseparator = "arrow"
#     buffer_index_type = 4
#     enable_tabline_filetype_icon = true
#     enable_statusline_mode = false
[[layers]]
name = 'core'
filetree_show_hidden = true
enable_smooth_scrolling = true
filetree_opened_icon = ''
filetree_closed_icon = ''

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#python'
python_interpreter = '/Users/mauwii/.pyenv/versions/neovim/bin/python3'

[[layers]]
name = "lang#go"

[[layers]]
name = "format"

[[layers]]
name = 'git'

[[custom_plugins]]
repo = "lilydjwg/colorizer"
merged = false

# #=============================================================================
# # dark_powered.toml --- dark powered configuration example for SpaceVim
# # Copyright (c) 2016-2023 Wang Shidong & Contributors
# # Author: Wang Shidong < wsdjeg@outlook.com >
# # URL: https://spacevim.org
# # License: GPLv3
# #=============================================================================



# # Enable autocomplete layer
# [[layers]]
#     name = 'autocomplete'
#     auto_completion_return_key_behavior = "complete"
#     auto_completion_tab_key_behavior = "smart"

# [[layers]]
#     name = 'shell'
#     default_position = 'top'
#     default_height = 30

# [[layers]]
#     name = "lang#python"
#     enabled_linters = ['python', 'pylint']
# # This is an example for adding custom plugins lilydjwg/colorizer
