#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2023 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================
# All SpaceVim option below [option] section
[options]
    automatic_update = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "lunaperche"
    colorscheme_bg = "dark"
    default_indent = 4
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    guifont = "FiraCode Nerd Font"
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false
    # filemanager = "defx"
    # filemanager = "neo-tree"
    project_rooter_patterns = ['.git/', '_darcs/', '.hg/', '.bzr/', '.svn/']
    project_rooter_outermost = false

[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_smooth_scrolling = true
    # filetree_opened_icon = ''
    # filetree_closed_icon = ''

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = 'lang#python'
    python_interpreter = '/Users/mauwii/.pyenv/versions/neovim/bin/python3'

[[layers]]
    name = "lang#go"

[[layers]]
    name = "format"

[[layers]]
    name = 'git'

[[layers]]
    name = 'VersionControl'

# [[custom_plugins]]
#     repo = "lilydjwg/colorizer"
#     merged = false
